model:
  model_name: "FDGC"

data_input: 
  dataset_name: IP
  classes: 16
  patch_size: 19

data_split:
  train_num: 100

network_config:
  max_epoch: 100
  learning_rate: 0.001
  lr_decay: 0.1
  lb_smooth: 0.01

result_output:
  path_weight: D:\PycharmProjects\HIC\FDGC\SaveModel\
  path_result: D:\PycharmProjects\HIC\FDGC\Results\




